stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: nginx:v1
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
