stages:
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: nginx:${CICD_EXECUTION_SEQUENCE}
    when:
      event:
        include:
        - push
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
