kind: Service
apiVersion: v1
metadata:
  name: nginx-example-service
spec:
  selector:
    app: nginx-example
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-example
  labels:
    app: nginx-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-example
  template:
    metadata:
      labels:
        app: nginx-example
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: nginx
        image: nginx:v1
        ports:
        - containerPort: 80
